config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :portfolios
  resources :pins

  get 'home/about'
  root to: 'home#about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show,:edit,:update,:destroy]
  layout 'pin'
  def index
    @pins = Pin.all.order("created_at DESC")
  end
  def show
  end

  def new
    @pin = current_user.pins.build
  end
  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Pin was successfully created"
    else
      render 'new'
    end
  end
  def edit

  end
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Successfully updated"
    else
      render 'edit'
    end
  end
  def destroy
    @pin.destroy
    redirect_to pins_path
  end
  end
  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end
  def find_pin
    @pin = Pin.find(params[:id])
  end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'

  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  def index
    @portfolio_items = Portfolio.all
  end
  def new
    @portfolio_item = Portfolio.new
  end
  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def show

  end



  private
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                  :subtitle,:body,
                                  :main_image,:thumn_image,
                                      )
  end
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/home/about.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div id="background"></div>

      <%= render "shared/application_nav" %>

      <%= render "shared/middlehomepagecontent" %>



    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monportfolio</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <%= yield %>



  </body>
</html>

app/views/layouts/pin.html.haml
!!! 5
%html
%head
  %title Pin Board
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Pin Board", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New Pin", new_pin_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"
    = yield

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Monportfolio</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= yield %>


</body>
</html>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  -if @pin.errors.any?
    #errors
      %h2
        = pluralize(@pin.errors.count, "error")
        prevented this Pin from saving
        %ul
          - @pin.errors.full_messages.each do |msg|
            %li=msg
  .form-group
    = f.input :image, input_html: {class: 'form-control'}
  .form-group
    = f.input :title, input_html: {class: 'form-control'}
  .form-group
    = f.input :description, input_html: {class: 'form-control'}
    =f.button :submit, class:"btn btn=primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Edit Your Pin
      .panel-body
        .current_image
          %strong.center Current Image
          = image_tag @pin.image.url(:medium)
        = render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      %h2= link_to pin.title, pin
      %p.user
        Submitted by

app/views/pins/new.html.haml
%h1 New Form

= render 'form'
= link_to "Back" , pins_path

app/views/pins/show.html.haml
= image_tag @pin.image.url(:medium)
%h1= @pin.title
%p= @pin.description
%p= @pin.user.email

= link_to "Back", pins_path
= link_to "Edit" , edit_pin_path
= link_to "Delete", pin_path, method: :delete, data: {confirm:"Are you sure ?"}

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<% @portfolio_items.each do |portfolio_item| %>
  <p><%= portfolio_item.title %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image %>
<% end %>

app/views/portfolios/new.html.erb
<div class="container ">
<%= form_for(@portfolio_item)  do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <%end%>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">

        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file<%= f.file_field :main_image ,style:'display:none'%>

        </label>

      </div>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file<%= f.file_field :thumn_image ,style:'display:none'%>

        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>


    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>

<% end %>
</div>

app/views/portfolios/show.html.erb
<h1><%= @portfolio_item.title %></h1>
<hr>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>
<hr>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= link_to "VACHIRAVIT", root_path %></h3>

    <ul class="nav masthead-nav">

      <li>
        <a href="#">Portfolio</a>
      </li>
      <li>
        <a href="#">About me</a>
      </li>
      <li>
        <a href="#">Contact</a>
      </li>
      <li>
        <a href="#">Album</a>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_middlecontent.html.erb
<div class="inner cover">
  <h1 class="cover-heading">
    <a href="" class="typewrite" data-period="2000" data-type='[ "this is shit.", "fuck.", "eiei้.", "I Love to Develop." ]'>
    <span class="wrap"></span>
  </a>
  </h1>
  <p class="lead">WTF</p>
</div>

app/views/shared/_middlehomepagecontent.html.erb
<div class="inner cover">
  <h1 class="cover-heading">Vachiravit Varojananuluck</h1>

  <p class="lead">Portfolio</p>

  <p class="lead"><a class="btn btn-lg btn-info" href="#">Find out
    more</a></p>
</div>